typedb/typeql

dependencies/maven/rules.bzl, deployment.properties, java/BUILD
We need to add the `deploy_maven_jar` bazel rule in order to create and deploy the maven Jar.
1) Added the `deploy_maven_jar` to `//java/BUILD` file
2) Updated `deployment.properties` to register `//java:graql` as as a maven package
=> Added Bazel rules for Maven deployment

grammar/Graql.g4, java/parser/Parser.java, java/parser/test/ParserTest.java
Improved `Parser.parseQuery()` core method to be simpler and check for nulls/empty, and updated Graql grammar to expect at least one query/pattern in `eof_query_list`/`eof_pattern_list`
=> Improved Parser.parseQuery()

java/exception/ErrorMessage.java, java/query/GraqlGet.java
`GraqlGet` subqueries enforce a validation check for variables to be within the scope of the query. And when validation not satisfied, it throws `GraqlException.variableNotInScope()` exception.
=> GraqlGet subqueries enforces variables to within scope

java/Graql.java, java/parser/test/ParserTest.java, java/property/HasAttributeProperty.java, java/property/HasAttributeTypeProperty.java, java/property/IsaProperty.java, java/property/RelatesProperty.java, java/property/RelationProperty.java
The term _"relationship"_ is a very frequently used term, and first-class citizen in our schema and query language. Yet it's too long and it could be shorter: _"relation"_.
Rename the term _"relationship"_ to _"relation"_.
=> Rename 'relationship' to 'relation'

grammar/Graql.g4, java/Graql.java, java/parser/Parser.java, java/property/RelationProperty.java, java/util/StringUtil.java
1) Graql did not restrict the use of "native types" (such as "entity", "relation", "attribute", "thing", "role" and "rule") at syntax parsing. It should.
2) There is currently no way for Graql users to easily refer to "native types" when constructing their Graql queries. In `graknlabs/grakn`, the query construction utilises `Schema.MetaSchema` enum, which contains the "meta types" in Grakn (which are the same as Graql "native types"), however, `Schema` is a low-level class that is used for the construction of the underlying binary graph. This access is inappropriate because it requires a dependency to a lower-level underlying class merely for constructing a query (which is a high-level user task), for example: `match $x isa ` + `Schema.MetaSchema.THING`.
1) We extend `label` to include …
=> Introducing 'native types' in Graql grammar and tokens

java/statement/builder/StatementInstanceBuilder.java, java/statement/builder/StatementTypeBuilder.java
Following PR #17, we want to also enable `.sub()` and `.isa()` methods on Graql `Statement`s to accept `Graql.Token.Type`
=> Overloaded Statement.sub() and .isa() to accept Graql.Token.Type

java/statement/builder/StatementTypeBuilder.java
Following PR #17, we want to also enable `.type()` method on Graql `Statement`s to accept `Graql.Token.Type`
=> Overloaded Statement.type() to accept Graql.Token.Type

java/Graql.java
Following PR #17, we want to also enable `.type()` method on main `Graql` class to accept `Graql.Token.Type`
=> Overloaded Graql.type() to accept Graql.Token.Type

java/query/GraqlGet.java
Fix null pointer error when trying to hash the GraqlGet - Aggregate subtype.
Ignore the `var` field if it is null
=> Ignore null in Graql Aggregate Hashcode

java/property/HasAttributeProperty.java, java/statement/Statement.java, java/statement/Variable.java
Clearer naming when indicating a variable is to be returned as part of the `get` clause. This is because in many places `asUserDefined` is not actually a user defined variable (especially in reasoner and QP) but instead used to ensure the variable is part of the `get` clause. This has lead to confusion about whether it's really about being able to check whether a variable was originally created by the user, or whether it's means to be returned in the `get`. The two main known use cases are:
1. Users creating variables with `var()`, then setting `asUserDefined()` to avoid creating a name for a variable they want to see in the `get()`
2. Internally, explicitly wanting to have the variable be returned.
Both boil down to creating anonymous variables that should be returned.
Rename …
=> Rename to asRetrievedVar() and isRetrieved

grammar/Graql.g4
Multiple community members and clients have asked for UTF-8 support in labels. Before this PR, we only support data instances having special characters (eg. attributes of `string` datatype), but we encountered errors when definining schema types with these characters, such as those documented in https://github.com/graknlabs/graql/issues/58 : `define Kläger sub entity;` fails.
An investigation revealed that this was perfectly definable using the direct methods on `Transaction`, so it is the Antlr grammar that fails to parse the extended character sets. This PR extends the allowed characters in the labels and implicit labels. To do this we borrow the regex for these valid variable names from Antlr's _internal_ allowed grammar (https://github.com/antlr/antlr4/blob/master/doc/lexicon.md). …
=> Extended label lexer

.circleci/config.yml, dependencies/graknlabs/dependencies.bzl, grammar/BUILD, grammar/Graql.g4, java/BUILD, java/parser/Parser.java, java/parser/test/ParserTest.java, java/property/TypeProperty.java, java/query/GraqlCompute.java, java/query/test/GraqlQueryTest.java, java/statement/Statement.java, java/util/StringUtil.java
In the previous definition of the Graql grammar, we had a "leak" in the token pattern definition of type labels and ID values. Both of them were defined by the same token `identifier`, which allowed both `ID_` patterns and `STRING_` patterns. `STRING_` pattern literally means anything. We've refined the grammar to restrict the definition of type labels and ID values, by directly assigning `type_label` and `ID_` tokens wherever they are expected, and removed the `identifier` token which allowed `STRING_` tokens to be provided. This change results in a more strict and consistent grammar, and therefore less error-prone.
- Refactored all of the token patterns for type labels (to have names beginning with `type_`
- Made `ID_` be independent of the definition of type labels
- Allowed `ID_` …
=> Restrict the token patterns for type labels and ID values

java/pattern/Conjunction.java, java/pattern/Disjunction.java, java/pattern/Negation.java, java/statement/Variable.java
During profiling it occurred to us that caching the hashCode of  `Variable` might be a good idea as it is called often. This PR introduces the change. Additionally we make equals and hashCode consistent for all patterns.
- cache Variable hashCode
- add missing hashCode/equals to `Negation` pattern
- regenerate `Conjunction` and  `Disjunction` equals and hashcodes so that all patterns have the same equality logic
=> Cache Variable hashCode and add missing negation hashCode&equals

dependencies/compilers/dependencies.bzl
Previously, a forked copy of `@rules_antlr` with several patches was used to generate ANTLR code. We can now use mainline repo since fixes we needed were merged.
Use `marcohu/rules_antlr#0.2.0` instead of `graknlabs/rules_antlr`
=> Revert @rules_antlr to use mainline repo

grammar/BUILD, java/BUILD
When deploying Maven JARs to Sonatype, the JARs are renamed to be `artifact-id-version.jar`, without the `group-id`. This is done in Sonatype because the JARs are organised into folders where the folder names represent the Group IDs. However, in certain build systems, e.g. Gradle, the JARs are collected under one directory, which means the JAR names are not unique enough to disambiguate itself from each other. We have now renamed the artifact ID of our Maven packages to be prefixed with `graql-` to solve this problem.
Prefixed artifact IDs of Maven packages with 'graql-' (fixes https://github.com/graknlabs/grakn/issues/5127, fixes https://github.com/graknlabs/bazel-distribution/issues/112).
=> Prefixed artifact IDs of Maven packages with 'graql-'

java/parser/Parser.java
A bug filed previously https://github.com/graknlabs/grakn/issues/5388 shows that `limit` is not applied to `match...delete` queries. An investigation showed that filters were not even leaving the Graql parser and becoming part of the parsed Graql objects.
* Flip the incorrect conditional in in `visitQuery__delete` so that filters are included instead of ignored, if they exist!
=> GraqlDelete Ignore limit filter

WORKSPACE
Newest changes in `bazel-distribution` (graknlabs/bazel-distribution#181) are backwards-incompatible.
Use workspace macros from most recent `bazel-distribution` version
=> Adapt to latest @graknlabs_bazel_distribution

.circleci/config.yml, grammar/BUILD, java/BUILD
graknlabs/bazel-distribution#191 changed the way Maven JARs are built. This PR adapts `graql` to latest changes
* Use `--define` to supply version to Maven deployment rule
* Remove `version_file` from `assemble_maven` arguments
=> Adapt to latest changes in bazel-distribution

grammar/Graql.g4, java/exception/ErrorMessage.java, java/exception/GraqlException.java, java/parser/test/ParserTest.java, java/property/ValueProperty.java
Enable and test the inclusion of fractions of seconds in a date time attribute value, up to 3 digits, allowing us to store up to 999 milliseconds.
For example, `2019-01-01T10:10:10.123` will now parse as having `10.123` seconds, and `2019-01-01T10:10:10.1` will parse as having `10.100` seconds
Closes #93 
* Implement and Test up to 3 digits after a `.` after seconds in a datetime
=> Datetime Milliseconds Decimal Representation

dependencies/graknlabs/dependencies.bzl
We have update build-tools to the one which connects to Maven Central with HTTPS.
=> Update build-tools in order to fix the HTTPS issue when accessing Maven Central

grammar/Graql.g4, java/Graql.java, java/parser/Parser.java, java/parser/test/ParserTest.java, java/property/ValueTypeProperty.java, java/query/test/GraqlQueryTest.java, java/statement/builder/StatementTypeBuilder.java
We are replacing the term `DataType` in `AttributeType` with `ValueType`). Previously, an `AttributeType` has a `DataType`. And an `Attribute` has `Value`. The type of `Value` is defined by `DataType`. We can see the inconsistency there. Now, `AttributeType` has `ValueType`, and `Attribute` has `Value`. The type of `Value` is `ValueType`. So it's all consistent.
- Renamed the `DataType` class to `ValueType`
- Renamed method names
- Renamed method arguments
- Renamed variable names
- Updated comments
=> Replaced the term 'DataType' with 'ValueType'

grammar/Graql.g4, java/exception/ErrorMessage.java, java/exception/GraqlException.java, java/parser/Parser.java, java/parser/test/ParserTest.java, java/query/GraqlDelete.java, java/query/MatchClause.java, java/query/test/BUILD, java/query/test/GraqlDeleteTest.java, java/query/test/GraqlQueryTest.java
Implementing the first step of https://github.com/graknlabs/graql/issues/115, we change the grammar to accept `statement_instance` for `delete` clauses, not just variables. As a medium term consequence, we remove the ability to limit, sort or offset delete queries.
* Change `variables` to `statement_instance` in `delete` clauses
* Update tests to reflect not just using variables
* Add new test to ensure query throws if `delete` variable not present in the `match`
* Remove `Filterable` from delete queries
=> Deletes accept statement_instance instead of variables

java/property/HasAttributeProperty.java
The prior PR removed `via` from the language, but failed to remove the `relation` statement that represents the implicit attribute relation. This is always created per `HasAttributeProperty`. We now remove it.
* Delete `relation` statement from `HasAttributeProperty`
This PR is actually also a step towards https://github.com/graknlabs/graql/issues/113
=> Remove implicit variable statement

.gitignore, grammar/Graql.g4, java/Graql.java, java/parser/Parser.java, java/parser/test/ParserTest.java, java/property/ValueClassProperty.java, java/query/test/GraqlQueryTest.java, java/statement/builder/StatementTypeBuilder.java
With the new hypergraph `AttributeType` implementation, we no longer need the `Enum` `ValueType` in the server. We just pass a Java class such as `Boolean.class`, `Long.class`, etc, whenever needed - which is very rare. So the term `ValueType` (that previously refers to the enum containing a class) is now being changed again, to `ValueClass` (referring to the explicit Java class). Additionally, I realise this would be even better for understandability, as the suffix `Type` implies that it is a "Grakn Type", which therefore should be inheritable and have instances - which is not true for `ValueClass`.
Additionally, we're also renaming `date` to `datetime` to accurately describe the actual class it represents, and also allow us to introduce a `date` value class to represent explicitly only …
=> Renamed 'ValueType' to 'ValueClass' and 'date' to 'datetime'

dependencies/graknlabs/dependencies.bzl
Prepare for release - use a tag instead of a commit
=> Use Previously Released Common 0.2.2

WORKSPACE, dependencies/graknlabs/repositories.bzl
Previously, we had to load gRPC dependency in `WORKSPACE` only to get access to `@bazel_skylib` (a dependency `bazel-distribution` required). This PR removes the unneeded dependency by upgrading `@graknlabs_dependencies` where it's loaded from the same macro as `bazel-distributon` is.
- Remove grpc from `WORKSPACE`
- Upgrade `@graknlabs_dependencies` to latest `master`
=> Remove unneeded dependency on gRPC

BUILD, dependencies/graknlabs/repositories.bzl
We also add a new toplevel BUILD file declaration for all targets used in CI and elsewhere to ensure these targets are correct at build time. We also bump the client-java commit.
=> Add filegroup declaring CI targets

java/pattern/Disjunction.java, java/test/behaviour/graql/GraqlSteps.java
Fix normalisation in Graql patterns - every match or insert pattern should be normalisable.
* Add missing case of `pattern.isVariable()` and `pattern.isNegation()` when normalising disjunctions, which led to casting errors.
* Graql BDD steps always try to normalise queries when possible.
=> Fix disjunction normalisation - missing sub-pattern cases

java/pattern/test/BUILD, java/pattern/test/Normalisation.java, java/pattern/test/NormalisationTest.java, java/pattern/variable/ThingVariable.java
Implement a basic pair of tests for normalisation of disjunctions and negated conjunctions of disjunctions. Also fix a casting error in the `.equals()` of `ThingVariable`.
* Test normaliation of disjunction
* Test normalisation of negated conjunction of disjunctions
* Fix a casting error when checking for equality in `ThingVariable`
=> Add normalisation tests for Disjunction and Negated sub-query

java/parser/Parser.java, java/parser/test/ParserTest.java, java/pattern/constraint/TypeConstraint.java
Fix a bug whereby Graql would not parse overriding of roles and attributes, in patterns such as `$x owns age as biometric;` , `$r relates father as parent;` etc
Parser was changed to correctly parse the overridden type. Three new tests were written in ParserTest to test overriding in relates, own and plays respectively. 
This exposed bugs in their respective toString method, which has now been fixed
=> Fixed parsing of played-role overriding, and printing of overridden types

dependencies/maven/artifacts.snapshot
Fix `build-dependency` that's currently red in CI
Fix `artifacts.snapshot` to be consistent with what Maven dependencies we depend on by running `dependencies/maven/update.sh`
=> Update artifacts.snapshot to fix build-dependency

java/query/GraqlInsert.java, java/query/GraqlWritable.java
In order to correctly handle relationship insertion, insert queries need a method for retrieving all relevant variables from them.
Implemented NamedUnboundVariables on GraqlInsert
=> Allow named unbound variables to be retrieved from insert & delete query

java/pattern/constraint/ThingConstraint.java
In order to handle deletion properly, we need to be able to distinguish Isa constraints placed implicitly as part of has. For example, `$x has name $y` implies `$y isa name`, but if we are deleting `$x has name $y` we should not also delete $y's isa constraint. To this end, we added a flag on the Isa constraint indicating if it was derived.
Added derived boolean to Isa constraint, set only when creating an isa implicitly via the Has constraints.
=> Mark Isa constraints derived via has constraints as derived

java/pattern/variable/builder/ThingVariableBuilder.java
As deleting a roleplayer now requires typeless has (to avoid a derived isa being present), we added a has overload to ThingVariableBuilder in order to construct a typeless has.
Adds has with signature of `T has(UnboundVariable variable)` to ThingVariableBuilder
=> Add typeless has to thing variable builder

grammar/Graql.g4, java/parser/Parser.java, java/query/GraqlMatch.java
To group together all the options available on a Match query, we create a `Modifier` object to hold `get` filter, and optional `limit`, `offset`, and `sort`
Create `GraqlMatch.Modifier` inner class to hold onto the modifiers available on a match query.
=> Create GraqlMatch.Modifier to group filters

java/query/GraqlMatch.java
To avoid code duplication in core, we modify `Modifiers.filter()` to return the set of all named variables if no filter is present.
* make `GraqlMatch.Modifiers` non-static
* always return non-empty list of filtered variables in `Modifiers.filter()`
=> Match modifier always returns non-empty filter

grammar/Graql.g4, java/Graql.java, java/common/exception/ErrorMessage.java, java/parser/Parser.java
Because Graql type label validation is complex, we've introduced a method `Graql.parseLabel` that can be used to validate that a String is a valid type label.
Add Graql.parseLabel
=> Add Graql.parseLabel for label validation

README.md
The README file mentions an incorrect date for the AGPL. This should say November 2007 instead of June 2007.
=> Correcting AGPL date in README

.grabl/automation.yml, BUILD, WORKSPACE, grammar/BUILD, grammar/TypeQL.g4, requirements.txt
Assemble and deploy `typeql-grammar` package to help TypeQL adoption
* Add a target that adapts grammar to Python language using a tool implemented in vaticle/dependencies#283
* Pass an adapted grammar to ANTLR code generator
* Add `//grammar:assemble-pip` and `//grammar:deploy-pip` targets that consume code generated by ANTLR and produce a Python package
=> Assemble and deploy TypeQL Python package

grammar/TypeQL.g4
To enable https://github.com/vaticle/typedb/issues/6434, we add in the grammar that sorting on multiple (ordered) variables is allowed.
* allow sorting on multiple variables
=> Allow sorting on multiple variables

WORKSPACE, dependencies/maven/artifacts.snapshot, dependencies/vaticle/repositories.bzl, grammar/BUILD
Assemble and deploy typeql-grammar package to allow Rust migration
* Add a target that adapts grammar to Rust language using a tool implemented in vaticle/dependencies#318
* Pass an adapted grammar to ANTLR code generator
* Add `//grammar:assemble-crate` and `//grammar:deploy-crate` targets that consume code generated by ANTLR and produce/deploy a Rust package
=> Assemble and deploy TypeQL Rust package

dependencies/vaticle/repositories.bzl, grammar/BUILD
Utilize the latest version of `assemble_crate` rule which automatically retrieves crate's dependencies from `rust_library`'s `deps` attribute
Upgrade `@vaticle_dependencies` to include fixes in vaticle/bazel-distribution#325 and vaticle/dependencies#331
=> Make typeql-grammar for Rust use the latest assemble_crate

.bazelrc, .gitignore, .grabl/automation.yml, BUILD, WORKSPACE, dependencies/maven/BUILD, dependencies/maven/artifacts.bzl, dependencies/maven/update.sh, dependencies/vaticle/BUILD, dependencies/vaticle/repositories.bzl, deployment.bzl, grammar/BUILD, grammar/TypeQL.g4, grammar/java/BUILD, grammar/python/BUILD, grammar/rust/BUILD, requirements.txt
We update the copyright header year to 2022.
Bump the vaticle-dependencies commit & replace the year 2021 with 2022 in each copyright header.
=> Bump copyright year to 2022

java/common/exception/ErrorMessage.java, java/pattern/schema/Rule.java
Enforce roles in the conclusion of a rule to be explicitly specified.
Since role-types in rule-conclusion must be unambiguous, requiring the user to explicitly specify them makes this clear to the reader and avoids nasty surprises.
This PR adds a syntax validation check 
- requiring all roles in a conclusion to be explicitly specified
- throws a newly introduced `TypeDBException.INVALID_RULE_THEN_ROLES` if they are not
=> Rule conclusion must explicitly specify role types

dependencies/vaticle/repositories.bzl
Bump commit-marker to update outdated typedb-common.  
Bumps commit-marker to recent master.
=> Bump typedb-common dependency

java/parser/test/ParserTest.java
We remove a test that used to test functionality that is no longer supported, namely, `match` queries with no named variables.
`testRoleTypeScopedSpecifically`: The test used to centre around the `match marriage relates spouse;` query at its conception. This is no longer supported, and the updated version is exactly equivalent to the preceding test.
`testQueryParserWithoutGraph`: This test was present in the initial commit, and it looks like it was testing that we can call a static method without referencing its class. Maybe it had a different use at some point prior, but that is lost to history.
=> Remove obsolete tests

grammar/TypeQL.g4, java/parser/Parser.java, rust/parser/mod.rs
We split the `delete` and `update` queries into separate parser rules in the TypeQL grammar, resolving a TODO in the process.
Split `delete` and `update` structures on grammar level, and modified the libraries accordingly.
Drive-by: remove unused `label_array` and `labels`.
=> Split delete_or_update in the grammar into separate parser rules

rust/common/mod.rs, rust/common/string.rs, rust/common/token.rs, rust/parser/mod.rs, rust/parser/syntax_error.rs, rust/parser/test/mod.rs, rust/pattern/conjunction.rs, rust/pattern/constraint/concept_constraint.rs, rust/pattern/constraint/thing_constraint.rs, rust/pattern/constraint/type_constraint.rs, rust/pattern/disjunction.rs, rust/pattern/mod.rs, rust/pattern/negation.rs, rust/pattern/variable/builder/concept_variable_builder.rs, rust/pattern/variable/builder/mod.rs, rust/pattern/variable/builder/thing_variable_builder.rs, rust/pattern/variable/builder/type_variable_builder.rs, rust/pattern/variable/concept_variable.rs, rust/pattern/variable/mod.rs, rust/pattern/variable/reference.rs, rust/pattern/variable/thing_variable.rs, rust/pattern/variable/type_variable.rs, rust/pattern/variable/unbound_variable.rs, rust/query/mod.rs, rust/query/typeql_match.rs, rust/typeql_lang.rs, rust/util/mod.rs
We complete the implementation of the match query building and parsing by adding handlers for inequality and string predicates and logical operations (and, or, not).
- Features:
- implement Concept variables along with the `is` constraint;
- implement Disjunction and Negation, finish Conjunction;
- handle non-equality (non-`=`) predicates;
- Refactoring:
- use concrete structs (not wrapped in enum) everywhere;
- unify `Display` trait implementations;
- clean up string formatting;
- replace hardcoded strings with string enumerations for keywords and operators;
- provide top-level builder macros that can handle arbitrary number of arguments that may be of different types.
=> Feature complete match query handling in TypeQL Rust

rust/common/date_time.rs, rust/common/mod.rs, rust/parser/mod.rs, rust/parser/test/mod.rs, rust/pattern/constraint/thing_constraint.rs, rust/pattern/mod.rs, rust/pattern/negation.rs, rust/pattern/variable/builder/thing_variable_builder.rs, rust/query/mod.rs, rust/query/typeql_delete.rs, rust/query/typeql_insert.rs, rust/query/typeql_match.rs, rust/query/typeql_update.rs, rust/query/writable.rs, rust/typeql_lang.rs
We implement the data write queries, viz. `delete`, `insert`, and `delete`-`insert`, aka "update".
Implement data structures, builder functions, and parser visitors for:
- insert query;
- delete query;
- update query (delete followed by insert).
Refactor:
- dedicated date_time module;
- simplified `has` building.
=> Implement Insert and Delete queries in Rust

java/pattern/Conjunction.java, java/pattern/Definable.java, java/pattern/Disjunction.java, java/pattern/Negation.java, java/pattern/Pattern.java, java/pattern/schema/Rule.java, java/pattern/variable/ConceptVariable.java, java/pattern/variable/ThingVariable.java, java/pattern/variable/TypeVariable.java, java/pattern/variable/UnboundVariable.java, java/pattern/variable/Variable.java, java/query/TypeQLDefinable.java, java/query/TypeQLMatch.java, java/query/TypeQLQuery.java, java/query/TypeQLUpdate.java, java/query/TypeQLWritable.java
We introduce an unformatted `toString` method which will not introduce any indentation or newlines.
This fixes a bug where a user's strings with newlines in them receive indentation in the middle of the attribute. Now, to avoid this visual or downstream effect the API exists to disable newlines and indentation.
* introduce `toString(boolean pretty)` which allows enabling or disabling pretty-printing. This API is available on `Defineable`, `TypeQLQuery`, and `Pattern`, but not `Constraint` since these are very short and don't do any pretty printing themselves.
* the default `toString()` on all objects does do pretty printing when the option is available
=> Introduce unformatted toString

rust/builder/mod.rs, rust/parser/mod.rs, rust/parser/test/mod.rs, rust/pattern/conjunction.rs, rust/pattern/constraint/thing/has.rs, rust/pattern/constraint/thing/isa.rs, rust/pattern/constraint/thing/relation.rs, rust/pattern/constraint/type_/owns.rs, rust/pattern/constraint/type_/plays.rs, rust/pattern/constraint/type_/relates.rs, rust/pattern/constraint/type_/sub.rs, rust/pattern/label.rs, rust/pattern/negation.rs, rust/pattern/variable/builder/concept.rs, rust/pattern/variable/builder/thing.rs, rust/pattern/variable/builder/type_.rs, rust/query/mod.rs, rust/query/typeql_delete.rs, rust/query/typeql_insert.rs, rust/query/typeql_match.rs, rust/query/typeql_update.rs, rust/query/writable.rs, rust/util/mod.rs
We create a macro emulating an unstable [try-blocks feature](https://doc.rust-lang.org/beta/unstable-book/language-features/try-blocks.html) that enables us to restrict the `Result<...>` return type to fallible function calls only. We also remove error propagation through builder functions.
Previously, in order to enable the unit tests, we returned Result from all builder functions and extended the builder functions to `Result<T, E>` as well as `T`. The new `try_!` macro allows us to use the `?` operator directly by wrapping the contents of the macro in an immediately evaluated lambda expression.
=> Remove error propagation and force error handling as early as possible

.factory/automation.yml, README.md, dependencies/vaticle/repositories.bzl
We've migrated our continuous integration for this repo to Vaticle Factory from Grabl.
We've updated:
- dependencies.
- uses of pyenv that are no longer in line with our approach.
- machine definitions from ubuntu 21.04 to 22.04.
=> Migrate to Factory

.factory/automation.yml, dependencies/vaticle/repositories.bzl
We've fixed the Python version learned from the successful GitHub deployment of typedb-common a definite working version of Python for this job.
We've bumped typedb-common and typedb-behaviour. We've also changed the used Python version to 3.7.9 from 3.7.12. This fixes a later bug where we attempt to link a library to a not-installed version of Python.
=> Bump dependencies and python version for GitHub deployment

.gitignore, BUILD, dependencies/ide/rust/BUILD, dependencies/ide/rust/sync.sh, dependencies/vaticle/repositories.bzl
We added the Rust IDE sync tool to enable Rust development in IDEs.
- Bump dependencies
- Add `dependencies/ide/rust/sync.sh`
- Add Cargo files and build artifacts to `.gitignore`
Run `./dependencies/ide/rust/sync.sh`, immediately after cloning/pulling this repo, or after loading it in an IDE.
This will generate `Cargo.toml` files in the project, allowing the Rust targets to be built, run and debugged using Cargo. The Vaticle fork of the IntelliJ Rust plugin is required: this modified plugin is able to run the `cargo` binary that is loaded into the Bazel sandbox on building the Bazel project.
=> Add Rust IDE sync tool

dependencies/vaticle/repositories.bzl, java/common/exception/ErrorMessage.java, java/pattern/schema/Rule.java
Enables disjunctions in rules, and updates rule-validation accordingly.
* Updates rule-validation to allow disjunctions in rule-conditions. 
* updates other validation steps to reflect disjunctions being allowed
- Every variable in the rule-then must be present in the trunk of the rule-when (i.e., outside negations and nested disjunctions).
=> Enable disjunctions in rules

dependencies/vaticle/repositories.bzl, rust/BUILD
We added `core-foundation-sys` and `libc` explicitly as Rust dependencies. They are conditional transitive dependencies of `antlr-rust` and `chrono` respectively. Due to https://github.com/vaticle/dependencies/issues/385 they are not included by default.
`core-foundation-sys` and `libc` are conditional dependencies of the `antlr-rust` and `chrono` crates. The condition is the Cargo condition `cfg('unix')`, which is supposed to represent any Unix system. Due to https://github.com/vaticle/dependencies/issues/385, they are not correctly pulled in when the machine has `aarch64` architecture. For now, we work around the issue by declaring them as explicit dependencies.
=> Add transitive Rust deps that aren't included by default on M1 Macs

dependencies/vaticle/repositories.bzl, rust/BUILD
We deleted some unnecessary Rust dependencies that were added to patch an issue building on M1 Macs in https://github.com/vaticle/typeql/pull/250.
We've fixed the `dependencies` repo so it correctly generates `BUILD` targets compatible with Apple Silicon, so now we can clean up our superfluous dependencies.
=> Delete Rust dependencies that were added to patch issue building on M1 Macs

dependencies/vaticle/repositories.bzl, rust/BUILD, rust/common/error.rs, rust/common/token.rs, rust/parser/mod.rs, rust/parser/test/mod.rs, rust/parser/typeql.pest, rust/pattern/conjunction.rs, rust/pattern/constraint/mod.rs, rust/pattern/constraint/type_/sub.rs, rust/pattern/disjunction.rs, rust/pattern/mod.rs, rust/pattern/negation.rs, rust/pattern/test/mod.rs, rust/pattern/variable/mod.rs, rust/query/mod.rs, rust/query/typeql_define.rs, rust/query/typeql_match.rs, rust/query/typeql_undefine.rs, rust/util/mod.rs
We implement pattern normalisation: a conjunction or a disjunction becomes a flat disjunction of conjunctions. Negations are not expanded.
Main change:
- implement normalisation routines.
Misc. drive-by improvements:
- implement missing validation checks;
- implement missing functionality: `sub!`, `isa!`;
- improve error reporting;
- refactoring:
- use enums for sort ordering;
- hide error templates from library users;
- clean up dodgy code (double references, redundant closures, etc.)
=> Pattern normalisation

WORKSPACE, dependencies/maven/artifacts.snapshot, dependencies/vaticle/repositories.bzl, rust/common/error/macros.rs, rust/util/mod.rs
We repackage the `error_message!` macro to be importable by other crates. That involved packaging all other macros used by `error_messages!` as private methods and internal rules within `error_messages!` (e.g. `max_code()` and `@format`). 
Helper macros are replaced by private constant functions generated by the macro where possible. The message formatting macro is replaced by an internal rule of the main `error_messages!` macro.
=> Export error enum generation macro

WORKSPACE, dependencies/vaticle/repositories.bzl, rust/BUILD, rust/tests/behaviour/BUILD
We update dependencies and the Bazel build files to reflect the new style of crate imports using crate-universe instead of cargo-raze.
=> Migrate to crate-universe

dependencies/vaticle/repositories.bzl, rust/BUILD
We update dependencies and explicitly specify the root of the typeql-rust crate. This allows us to have non-`lib.rs` root to our library in the assembled crate. Cf. https://github.com/vaticle/bazel-distribution/pull/366
=> Update crate assembly

dependencies/ide/rust/sync.sh, java/parser/test/ParserTest.java, rust/parser/test/mod.rs, rust/pattern/negation.rs, rust/pattern/schema/rule.rs
We update the way rules and queries are printed in the TypeQL rust implementation, following the format introduced in #275.
=> Update rule printing in TypeQL Rust

BUILD, dependencies/vaticle/repositories.bzl, grammar/python/BUILD
We fix the issue with grammar-python producing empty pip packages.
`rules_antlr` cheats: since the `py_library` expects `*.py` sources, `antlr(language = "Python3")` names the package _folder_ `*.py` so that the `py_library()` rule would accept its output as an input. Unfortunately, the current version of `py_library()` is not so easily tricked and produces `error: can't copy 'bazel-bin/grammar/python/python-src.py': doesn't exist or not a regular file`.
In this PR, we explicitly redeclare the python sources produced by the `antlr()` rule for use by `py_library()`.
Drive-by: fix top-level checkstyle to _exclude_ rather than include the bazel remote cache files.
=> Fix TypeQL Python build

grammar/TypeQL.g4, java/common/TypeQLToken.java, java/common/exception/ErrorMessage.java, java/parser/Parser.java, java/parser/test/ParserTest.java, java/pattern/constraint/TypeConstraint.java, java/pattern/variable/builder/TypeVariableBuilder.java
We generalise the annotation syntax and parsing to be able to handle a new type of annotation: the `@unique` annotation, which is available only on the `owns` constraint:
```
define
person sub entity, owns email @unique;
email sub attribute, value string;
```
This annotation indicates that any `email`s a person owns must be unique to that person. It does not place any restrictions on the number of emails any given person may own.
The language builder API has also been updated to use a generalised form of any number of annotations, rather than having a particular boolean per annotation type (now, pass annotation `UNIQUE` or `KEY` instead of booleans).
* Introduce `annotations_owns` in the grammar
* Introduce new grammar rules for `annotations`: `@key` becomes an `annotation`, as does the …
=> Introduce unique annotation

rust/query/typeql_match.rs
As per the Rust compiler:
```
warning: unnecessary parentheses around type
|
306 | impl<const N: usize> From<([(&str, token::Order); N])> for Sorting {
|                           ^                         ^
|
= note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
|
306 - impl<const N: usize> From<([(&str, token::Order); N])> for Sorting {
306 + impl<const N: usize> From<[(&str, token::Order); N]> for Sorting {
|
```
We've removed some unnecessary parentheses from an `impl` block signature.
=> Remove unnecessary parentheses

rust/pattern/schema/rule.rs
While parsing a rule with `has` and without relation in `then` part `expect_valid_inference()` function panicked. Now it returns an `Error`.
We incorporated `expect_infer_single_edge()` function into `expect_valid_inference()`.
=> Fix rule validation

rust/parser/mod.rs, rust/parser/test/mod.rs
While parsing `Variable`, `visit_pattern_variable()` panicked because of incorrect argument format. We fixed it and added unit tests. Similar errors ware while parsing `definables` and `patterns`.
- We extracted subtree with `pattern_variable` as a root before passing it to `visit_pattern_variable()`.
- We extracted subtree with `definables` as a root before passing it to `visit_definables()`.
- We fixed an error in `visit_eof_patterns()` function: it tried to extract `eof_patterns` instead of `patterns`.
- We added unit test for parse functions that wasn't covered.
=> Fix Rust parser for definables and variables

rust/common/error/macros.rs
We improve the debug formatting for macro-generated errors, by including more detail about the error. This solves issue https://github.com/vaticle/typedb-client-rust/issues/44
We include the error code and error message in the debug format for macro-generated errors. We do this by explicitly implimenting `std::fmt::Debug`, inserting the error code and error message.
=> Debug formatting Errors

rust/common/error/macros.rs
We implement the `format_code()` accessor for the generated error types, as well as expose the `PREFIX` string.
=> Implement formatted code accessor for the TypeQL/common error macro

dependencies/vaticle/repositories.bzl, java/common/exception/ErrorMessage.java, java/pattern/schema/Rule.java, java/test/behaviour/typeql/TypeQLSteps.java
Check that relation variables used to infer new relations in then clause should be anonymous
- Updated TypeDB behaviour dependency.
- Added error message to display in case of exception thrown from the check.
- Added test to check if the relation reference variable in then clause is anonymous.
=> Relation variable name in rule 'then' must not be present.

rust/builder/mod.rs, rust/common/error/macros.rs, rust/parser/test/mod.rs, rust/pattern/mod.rs, rust/pattern/test/mod.rs, rust/query/mod.rs, rust/util/mod.rs
Problem is described in #298: we have macros that need access to other items in our crate. Paths to these items were not absolute, and users had to import that particular items and were able to use their own objects with the same names and use it in the macros. Now all paths are absolute, based on the `$crate` metavariable.
- We updated all macros that need access to other items in the crate.
- We removed redundant imports. 
closes #298
=> Sanitise rust macros to avoid forcing user's environment

dependencies/vaticle/repositories.bzl, rust/parser/test/mod.rs, rust/pattern/test/mod.rs
We update to pest and pest-derive v2.7.4, which among other things purports to fix the error where [deriving Parser fails on "undeclared crate or module `alloc`"](https://github.com/pest-parser/pest/issues/899) (https://github.com/pest-parser/pest/pull/900).
We also clean up some compile warnings (unused imports and hashes).
=> Update pest 2.4.0 => 2.7.4 

.factory/automation.yml, README.md, RELEASE_NOTES_LATEST.md, RELEASE_TEMPLATE.md, WORKSPACE, dependencies/maven/artifacts.snapshot, dependencies/vaticle/repositories.bzl, grammar/README.md, grammar/java/BUILD, grammar/python/BUILD, java/BUILD, java/README.md, java/builder/BUILD, java/common/BUILD, java/parser/BUILD, java/pattern/BUILD, java/query/BUILD, java/test/deployment/pom.xml, rust/BUILD
Updates artifact deployment & consumption rules to use cloudsmith instead of the self-hosted sonatype repository.
* Bumps repository dependencies, Updates deployment targets
=> Migrate artifact hosting to cloudsmith

.factory/automation.yml
We add a sync-dependencies job to be run in CI after successful snapshot and release deployments. The job sends a request to vaticle-bot to update all downstream dependencies.
Note: this PR does _not_ update the `dependencies` repo dependency. It will be updated automatically by the bot during its first pass.
=> Sync dependencies in CI

dependencies/maven/artifacts.snapshot, java/query/builder/ProjectionBuilder.java, rust/pattern/constraint/type_/owns.rs
We note a previous change in [2eef07d388391e073cc1631f5af2bbf15e844cc4](https://github.com/vaticle/typeql/commit/2eef07d388391e073cc1631f5af2bbf15e844cc4) and extend it here to refactor the TypeQL Fetch projection query builder:
Usage rename, before:
```
cVar("x").map("name")
label("subquery").map(TypeQL.match(...).fetch(...))
```
Usage now: 
```
cVar("x").fetch("name")
label("subquery").fetch(TypeQL.match(...).fetch(...))
```
Fetching multiple attributes without relabeling, before:
```
cVar("x").fetch(list(pair("name"), null), pair("age", null), pair("dob", null)))
```
Usage now:
```
cVar("x").fetch("name", "age", "dob")
```
Previously, we renamed the `.map()` builder method to `.fetch()`
We additionally clean up the attribute projection builder to allow specifying a list of attribute to …
=> Refactor TypeQL Java projection builder

dependencies/maven/artifacts.snapshot, dependencies/vaticle/repositories.bzl
Bump snake-yaml maven dependency to 2.2
Bumps `vaticle_dependencies` to include update snake-yaml to version  2.2.
=> Bump snake-yaml maven dependency to 2.2

java/common/exception/ErrorMessage.java, rust/common/error/mod.rs
We fixed various grammatical issues in the Java and Rust error messages.
- Fix various grammatical issues in Java `ErrorMessage` class
- Fix various grammatical issues in Rust `error/mod.rs`
=> Java and Rust error messages: grammatical fixes

java/common/exception/ErrorMessage.java, rust/common/error/mod.rs
We fixed various logical and grammatical issues in the Java and Rust error messages, aiming to have similar errors from both implementations.
* Add missing error messages update initiated in https://github.com/vaticle/typeql/commit/99bb587 for one of the languages.
* Update error message for valid labels format, broadening the leading character restrictions.
=> Update error messages to match Rust and Java implementations

grammar/python/BUILD, rust/BUILD
The `author` field of our Python grammar and Rust library is now **TypeDB Community** with the email being **community@typedb.com**.
The former labels "Vaticle" and "community@vaticle.com" are no longer applicable and have been replaced.
=> Make the author of the Python grammar and TypeQL Rust "TypeDB Community"

rust/annotation.rs, rust/parser/annotation.rs, rust/parser/expression.rs, rust/parser/literal.rs, rust/parser/mod.rs, rust/parser/pipeline.rs, rust/parser/statement/thing.rs, rust/query/pipeline/stage/modifier.rs, rust/statement/comparison.rs, rust/typeql.rs, rust/value.rs
Make fields for expression public + Add finer literal parsing
We now recurse to the leaves of the grammar when parsing literals. The literals hold the parts instead of a single string.
=> Make fields for expression public & Add finer literal parsing

rust/annotation.rs, rust/parser/define/type_.rs, rust/parser/redefine.rs, rust/parser/test/aggregate.rs, rust/parser/test/mod.rs, rust/parser/test/schema_queries.rs, rust/parser/typeql.pest, rust/query/pipeline/stage/insert.rs, rust/schema/definable/type_/mod.rs
Updates the grammar to allow standalone type-declarations.
This change arises from changing `mytype sub entity` to `entity mytype`. 
* Type annotations are now directly on the declaration  rather than on the `sub` capability.
Makes a few fields pub as well.
=> Allow type declarations without capabilities

rust/parser/define/type_.rs, rust/parser/typeql.pest, rust/schema/definable/type_/capability.rs
Previously, we could only use not scoped labels (names without scopes) in `as` of `plays`. However, it can cause troubles while reading the schema by a human eye:
```
define
relation family relates father;
relation fathership relates father;
entity person plays family:father, plays fathership:father;
relation subfamily sub family, relates subfather as father;
relation subfathership sub fathership, relates subfather as father;
entity subperson sub person, plays subfamily:subfather as father, plays subfathership:subfather as father;
```
This PR allows us to use both
`entity subperson sub person, plays subfamily:subfather as family:father, plays subfathership:subfather as fathership:father;`
and 
`
entity subperson sub person, plays subfamily:subfather as father, plays …
=> [3.0] Change plays override from label to named_type to allow both scoped and not scoped labels

rust/common/token.rs, rust/parser/define/function.rs, rust/parser/pipeline.rs, rust/parser/test/aggregate.rs, rust/parser/test/fetch.rs, rust/parser/test/mod.rs, rust/parser/typeql.pest, rust/query/pipeline/stage/fetch.rs, rust/query/pipeline/stage/reduce.rs, rust/schema/definable/function.rs
We introduce the missing `reduce` keyword for operations like `min/max/count` aggregations, as well as `first()` and `check`. However, we do not require the `reduce` keyword for function return statements:
```
match
...
reduce count($x);
```
in a function would be;
```
define 
fun test(...) -> long:
match ...
return count($x);
```
We also allow trailing commas throughout the grammar, though they are ignored, to allow the user to generate queries more simply:
```
match
$x, isa person, has name $n, ... ; #equivalent to the user-friendly syntax: $x isa person, has name, ...;
```
=> Introduce Reduce keyword for stream reduction operations

rust/parser/define/type_.rs, rust/parser/statement/type_.rs, rust/parser/test/schema_queries.rs, rust/parser/typeql.pest, rust/parser/undefine/mod.rs, rust/schema/definable/type_/capability.rs, rust/schema/undefinable/mod.rs, rust/statement/type_.rs
Rename override to specialise. Remove specialisations for owns and plays respecting the server's changes: https://github.com/typedb/typedb/pull/7157
=> Rename override to specialise. Remove specialisations for owns and plays

WORKSPACE, rust/parser/literal.rs, rust/parser/statement/thing.rs, rust/parser/typeql.pest, rust/query/pipeline/stage/fetch.rs, rust/query/pipeline/stage/reduce.rs, rust/schema/definable/struct_.rs, rust/statement/mod.rs, rust/statement/thing/mod.rs, rust/typeql.rs, rust/value.rs
We now accept the ISO 8601 duration literal format (`P3Y6M4DT12H30M5.346S`) in TypeQL queries.
=> Implement duration literal parsing

rust/common/token.rs, rust/parser/pipeline.rs, rust/parser/test/aggregate.rs, rust/parser/test/fetch.rs, rust/parser/test/group_aggregate.rs, rust/parser/test/mod.rs, rust/parser/typeql.pest, rust/query/pipeline/stage/reduce.rs
Update syntax for reduce stages in pipelines. Example: `reduce $max = max($of1), $sum = sum($of2) within ($group, $variables)`
Update syntax for reduce stages in pipelines
=> Update syntax for reduce stages in pipelines

rust/common/token.rs, rust/parser/pipeline.rs, rust/parser/typeql.pest, rust/query/pipeline/stage/modifier.rs
Implement the 'require' clause:
```
match
...
require $x, $y, $z;
```
Will filter the match output stream to ensure that the variable `$x, $y, $z` are all non-empty variables (if they are optional).
=> Implement require operator

rust/common/token.rs, rust/parser/define/function.rs, rust/parser/mod.rs, rust/parser/pipeline.rs, rust/parser/statement/mod.rs, rust/parser/test/fetch.rs, rust/parser/typeql.pest, rust/query/pipeline/stage/fetch.rs, rust/query/pipeline/stage/mod.rs, rust/query/pipeline/stage/modifier.rs, rust/query/pipeline/stage/reduce.rs, rust/schema/definable/function.rs
We refactor Fetch and Function behaviour, to allow any of the following Fetching patterns:
```
match
...
fetch {
// fetch a matched attribute, value, or type. Represented as a attribute/value/type or null (if the variable is optional).
"single variable": $a,   
// attribute 'age' of $x. Must be `@card(0..1)` or `@card(1..1)`. Represented as an attribute or null.
"single-card attributes": $x.age,
// all attributes 'name' of $x. Can be any cardinality.
"list higher-card attributes": [ $x.name ], 
// inline-computed expression value. Represented as a value.
"single value expression": $a + 1,  
// an inline query with a 'return' block to select a *single* answer. Represented identically to a single variable or null.
"single answer block": (  
match
$x has name $name;
return first $name;
),
// …
```
=> Implement full fetch specification

rust/common/mod.rs, rust/typeql.rs
We make `identifier` and `common` `mod`s public to reuse their symbols in [typedb](https://github.com/typedb/typedb/pull/7208).
=> Make `identifier` and `common` mods public to reuse in typedb

rust/schema/undefinable/mod.rs
We add `Clone` trait to undefinable structs to be able to save a copy of this struct without moving the whole `Undefinable` enum.
Similarly to `enum Definable`
=> Add Clone trait to undefinable structs

rust/statement/mod.rs
We make the `lhs` and `rhs` fields of the `Is` statement struct public for use in typedb core.
=> Make Is statement fields public

rust/value.rs
We add a separate `unescape` method for strings inside `regex` annotations to preserve regex escaped characters and unescape `"` quotes.
=> Add unescape version for regex annotations

rust/parser/typeql.pest
We reorder fetch variants to prioritize the fetch stream for functions over the list of expressions. The old ordering led to incorrect parsing of fetch statements with listed function calls.
=> Reorder fetch variants to prioritize the fetch stream for functions over the list of expressions

.factory/automation.yml, rust/parser/define/function.rs, rust/parser/redefine.rs, rust/parser/test/functions.rs, rust/parser/test/mod.rs, rust/parser/typeql.pest, rust/query/schema/define.rs, rust/schema/definable/function.rs, rust/schema/definable/type_/mod.rs
Adds function redefine syntax, and some small changes.
* Add function redefine
* Makes some fields public
* Functions keep their unparsed string representation so the function manager can store it.
=> Add function redefine, other small changes for functions

rust/common/token.rs, rust/parser/statement/mod.rs, rust/parser/statement/single.rs, rust/parser/statement/thing.rs, rust/parser/test/builtin_functions.rs, rust/parser/test/disjunctions.rs, rust/parser/test/match_queries.rs, rust/parser/test/mod.rs, rust/parser/test/modifiers.rs, rust/parser/test/schema_queries.rs, rust/parser/test/sugar.rs, rust/parser/type_.rs, rust/parser/typeql.pest, rust/statement/mod.rs, rust/statement/thing/isa.rs, rust/statement/thing/mod.rs
Adds `let` keyword before assignments & moves the constraint on an `isa` to the end. E.g. `$x isa marriage ($a, $b)`
=> TypeQL syntax updates

rust/common/token.rs, rust/parser/pipeline.rs, rust/parser/test/group_aggregate.rs, rust/parser/typeql.pest, rust/query/pipeline/stage/reduce.rs
We rename `within` to `groupby`, in better alignment with expected terminology.
- Rename `within` to `groupby`
=> Rename within to groupby

rust/parser/literal.rs, rust/parser/test/match_queries.rs, rust/parser/typeql.pest, rust/value.rs
Require decimal literals to be suffixed with 'dec'
Updates grammar & datastructures.
=> Add 'dec' suffix to decimal literals

rust/parser/define/struct_.rs, rust/parser/define/type_.rs, rust/parser/pipeline.rs, rust/parser/statement/type_.rs, rust/parser/type_.rs, rust/parser/typeql.pest, rust/schema/definable/function.rs, rust/schema/definable/struct_.rs, rust/statement/type_.rs, rust/type_.rs
Restrict by grammar refactoring type_ref and named_type
We notice the two distinct uses of `type_ref` and `named_type` and decide to separate them, allowing for less inapplicable cases during translation to server IR.
=> Restrict by grammar refactoring type_ref and named_type

dependencies/typedb/repositories.bzl, rust/Cargo.toml
Update dependencies and the generated Cargo files for the newest version of the target repo.
=> Update dependencies to avoid conflicts with the server

rust/parser/define/type_.rs, rust/parser/statement/type_.rs, rust/parser/test/mod.rs, rust/parser/typeql.pest, rust/schema/definable/type_/capability.rs, rust/statement/type_.rs
We fix one syntactic inconsistency, grammatically allowing list overrides for relation's roles:
```
define
relation sub-rel, relates sub-role[] as super-role[];
```
We relax the grammar to allow specialisations of relation's roles with ordering.
=> Allow relates overrides to have lists
