.circleci/config.yml
dependencies/graknlabs/dependencies.bzl

The `deploy-maven-test` CI job deploys the `graql.lang` Maven artifact to the Maven snapshot repository

Implement deploy-maven-test

---

java/query/GraqlGet.java

Fix NullPointerException in `hashCode` with GraqlGet - Aggregate
Fix two places where `var` could be null and ignore these nulls in the `hashCode` method

Fix aggregate hashcodes

---

BUILD

Add release title in the Github draft.

Add release title in the Github draft

---

grammar/Graql.g4

Clean up forgotten unused keyword
Remove aggregate as a reserved keyword

Remove aggregate as a reserved keyword

---

.circleci/config.yml
dependencies/graknlabs/dependencies.bzl

We have added release-validation of `graknlabs_common`

Add release-validate for graknlabs_common

---

test/deployment/pom.xml

We have fixed a bug in the test deployment where the release repository is not included.

Add the maven release repository in test deployment

---

java/query/test/GraqlQueryTest.java

Test `Graql.parse` and `Graql.parseList` with multiline queries.
* Add new test cases

Add two tests for parsing query and query list

---

java/query/test/GraqlQueryTest.java

Revert "Add two tests for parsing query and query list"

---

grammar/Graql.g4
java/Graql.java
java/parser/Parser.java
java/parser/test/ParserTest.java
java/property/ValueTypeProperty.java
java/query/test/GraqlQueryTest.java
java/statement/builder/StatementTypeBuilder.java

Decided to stick with ValueType instead of ValueClass
* revert some of the changes from #126

Revert rename to ValueClass from ValueType

---

grammar/Graql.g4
java/Graql.java
java/parser/Parser.java
java/parser/test/ParserTest.java
java/property/HasAttributeProperty.java
java/statement/builder/StatementInstanceBuilder.java

We got into a dependency mess because I over-eagerly removed implicit relations/`via` etc. from graql. This PR removes them from master, and they will be separately added in a branch for development
* Undo #124  and #125

Revert Remove Implicits

---

.circleci/config.yml
WORKSPACE
dependencies/graknlabs/dependencies.bzl

Use Ubuntu 16 Image and update build tools

Use Ubuntu 16 Image and update build tools

---

.bazelrc
.grabl/automation.yml

- Use new `graknlabs-ubuntu-20.04` image
- Remove RBE setup boilerplate
- Enable release workflow

Update automation yml

---

WORKSPACE
dependencies/graknlabs/repositories.bzl

We have refactored the WORKSPACE file to make it clearer. The key thing we did was to properly enclose declarations into appropriate sections.

Refactor WORKSPACE

---

.grabl/automation.yml

Make Maven release depend on GitHub deployment
Make Maven release depend on GitHub deployment

Make Maven release depend on GitHub deployment

---

java/pattern/variable/Reference.java

* Change name of class from "Referrable" to "Referable"
* Change name of class from "Referrable" to "Referable"

Fixed Referable Class Typo

---

java/parser/Parser.java

We fixed the issue in the correctness test in Grabl.
IntelliJ automatically batches imports from the same class into * import, which is not allowed by checkstyle. 
We fixed that code.

Fix the checkstyle error in grabl correctness test

---

WORKSPACE
dependencies/vaticle/repositories.bzl
grammar/BUILD

Update usage of `@rules_antlr` to match latest `@vaticle_dependencies`
Use the latest release of `rules_antlr` and update usage accordingly

Upgrade @rules_antlr usage

---

.grabl/automation.yml
BUILD
LICENSE
dependencies/maven/BUILD
dependencies/vaticle/BUILD
dependencies/vaticle/repositories.bzl
grammar/BUILD
grammar/java/BUILD
grammar/python/BUILD
grammar/rust/BUILD
java/BUILD
java/LICENSE
java/common/BUILD
java/parser/BUILD
java/parser/test/BUILD
java/pattern/BUILD
java/pattern/test/BUILD
java/query/BUILD
java/query/test/BUILD
java/test/BUILD
java/test/behaviour/debug/BUILD
java/test/behaviour/typeql/BUILD
rust/BUILD
rust/LICENSE

We introduce a test that ensures that the license text is correct.
* Bring all the `checkstyle_test()` invocations in line with the updated definition in dependencies;
* Use checkstyle to confirm that each license text is correct.

Extend license checkstyle tests and update licenses

---

dependencies/vaticle/repositories.bzl
rust/BUILD
rust/pattern/constraint/type_/mod.rs
rust/pattern/constraint/type_/regex.rs

We perform validation of the regex in a `RegexConstraint`.
We add a `regex` crate dependency via dependencies and add the missing validation check to the constraint.

Regex validation

---

rust/common/error/mod.rs

We implement cloning, equality comparison, and the standard error trait for the main `Error` type.

Implement common error traits for Error

---

.factory/automation.yml

We enable the TypeQL Rust crate deployment jobs in CI.

Enable Rust crate deployment

---

README.md

Update the readme file to fix the forum badge.
Update the forum badge.

Update readme: fix the forum badge

---

rust/common/identifier.rs
rust/expression/mod.rs
rust/query/pipeline/mod.rs
rust/query/pipeline/stage/reduce.rs
rust/schema/definable/function.rs
rust/statement/mod.rs

Updates fields used by function builders in core to be public.
Update fields used by function builders in core to be public

Update fields used by function builders in core to be public

---

rust/query/pipeline/stage/delete.rs
rust/query/pipeline/stage/modifier.rs
rust/query/pipeline/stage/put.rs
rust/query/pipeline/stage/update.rs
rust/statement/thing/mod.rs

Make fields used by pipelines & delete queries public
Make fields used by pipelines & delete queries public

Make fields used by pipelines & delete queries public

---

rust/parser/statement/thing.rs
rust/parser/test/write_queries.rs
rust/statement/thing/mod.rs

Expose some more required fields.
Expose some more required fields.

Expose some extra fields in statements

---

rust/common/mod.rs
rust/parser/define/function.rs
rust/parser/mod.rs
rust/parser/pipeline.rs
rust/parser/typeql.pest
rust/query/pipeline/stage/fetch.rs
rust/schema/definable/function.rs

Further refactoring required for the fetch implementation.

Fetch enhancements

---

.factory/automation.yml

Disable dependency-analysis

---

dependencies/typedb/repositories.bzl
rust/Cargo.toml

Update dependencies reference to avoid conflicts with TypeDB server.

Update dependencies reference
